* Titre
* Contexte Historique
Résumons rapidement sa vie.
Voltaire (né François-Marie Arouet, 1694-1778) était une philosophe français.
Il écrivait plus de 2000 livres/brochures et plus de 20.000 lettres, mais Candide et, sans doute, son ouvrage la plus populaire.
Aussi, il y avait plusieur affaires d'amour.

Son premier ouvrage, Oedipe /edip/, a été écrit quand Voltaire a été incarcéré.

Image: La Bastille pendant la revolution, mais Voltaire était mort une dizaine d'années avant que ça ait commencé.

* Résumé de Candide
Le problème (qui resemble problèmes dans la vie de Voltaire) est que Cunégonde est la fille de le baron.

Inévitablement, Candide l'embrasse et il est exilé de le château.

Pangloss dit: "Remarquez bien que les nez ont été faits pour porter des lunettes; aussi avons-nous des lunettes."
Tr: Nose is formed for glasses, therefore we wear glasses.

Voltaire se moquer de Leibniz et sa philosophie, mais il l'exagére: Leibniz n'était pas assez naïf que Pangloss.  Au contraire, beaucoup de monde le respectent.

C'est Voltaire quand il était agé; il a toujours un sourire.

* Résumé 2
6. Pendant les voyages, Pangloss est pendu (mais il s'échappe), Candide trouve Cunnégond, qui est
   vivant.  Il a besoin de tuer ses ravisseurs (propriétaires), et ils fuient
   l'Europe ensemble au Monde Nouveau.
* Résumé 5
Pangloss: "Je suis toujours de mon premier sentiment, car enfin je suis philosophe : il ne me convient pas de me dédire, Leibnitz ne pouvant pas avoir tort."
* Thèmes
Un grand philosophe, près de la fin du livre: "Qu'importe, dit le derviche, qu'il y ait du mal ou du bien? Quand Sa Hautesse
envoie un vaisseau en Égypte, s'embarrasse-t-elle si les souris qui sont dans le
vaisseau sont à leur aise ou non?"

Leibniz: Pangloss a dit "Leibnitz ne pouvant pas avoir tort".
